### PR TITLE
[BP-948] Migrating examples bucket to 207 account

### PR DESCRIPTION
**Pull request by vigneshk96**
Migrating bodo-examples-data from 481 account to bodo-example-data on 207 account. After deleting on 481, we can have the name corrected.

### CODE REVIEW

**Review by sahil1105 — COMMENTED** [review]
Looks fine to me, but needs a second review to verify everything works.

**Comment by alifarhid** [comment]
Hi Vignesh, 
Could you shed some light on why we are moving to another account, and with a different bucket name? We had no choice other than changing the bucket name? Couldn't we move the data to a temp bucket, delete the bodo-examples-data bucket from 481 and make the bucket name available for 207, rename the temp bucket to bodo-examples-data?
For example one case I know is the OpenTeams team which we directed them to use our bucket, they made examples and probably even recorded the video. 
Anyhow, it's not a big deal, just wanted to know some background so if they asked I can address.
Thank you.

**Comment by vigneshk96** [comment]
481 is the platform account and we want to keep public resources out of it, along with that we have SOC2 audit as well for the platform which this will not comply with.
We are keeping both buckets to avoid downtime, we can eventually do the swapping back to bodo-examples-data when we expect no traffic on this bucket.

**Review by alifarhid — APPROVED** [review]
@vigneshk96 your reason for doing this migration makes sense. Thanks. One more question: the data is already loaded to Bodo-example-data bucket right? I am approving these changing under contingency that @hadia206 and @ritwika314 run them one time e2e.

**Comment by hadia206** [comment]
I tested two files and it worked with me.

**Comment by ritwika314** [comment]
> Yes, I have copied all the data into the new bodo-example-data bucket already. Waiting for Hadia/Ritwika to test it 👍

Tested taxi and beer reviews E2E and it worked.

**Pull request merged**
